Update ci.yml
Signed-off-by: Tim Burns <92951498+OpenSource-For-Freedom@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,6 +31,11 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y equivs devscripts
           cd $GITHUB_WORKSPACE
+          if [ ! -f debian/control ]; then
+            echo "ERROR: debian/control file not found!"
+            ls -l debian
+            exit 1
+          fi
           equivs-control debian/control
           sudo mk-build-deps -i debian/control --tool "apt-get -y"
 
